### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by 1995parham** [pi0/farsi.css#1]
سلام پویا :)
ببین پویا من خیلی وب کار نیستم ولی به نظرت میشه این ریپوات را طوری کرد که بشه با یک کلون ساده از ازش توی هر پروژه‌ای استفاده کرد ؟

**Comment by pi0** [comment]
سلام پرهام مرسی از بررسیت :) آره سیستم کامپوزر میتونه پکیج کنه و راحت بشه توی پروژه ی وب اضافه کرد.
https://getcomposer.org
راستش این ریپو خیلی تصادفی و سریع ساخته شد. حتما اینکارو میکنم :)

**Comment by 1995parham** [comment]
خیلی مرسی پویا :+1: 
واقعا به نظرم خیلی چیز خوبی هست
